import type { AppProps } from "next/app";
import Head from "next/head";
import "../styles/global.css";
import { DeviceTypeProvider } from "@/contexts/DeviceTypeContext";

export default function App({ Component, pageProps }: AppProps) {
  return (
    <>
      <Head>
        <title>판다마켓</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/ic_logo.svg" />
      </Head>
      <DeviceTypeProvider>
        <Component {...pageProps} />
      </DeviceTypeProvider>
    </>
  );
}
